version: '3.8'
services:
  web:
    image: php:7.4-apache
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
